======= stdin =======
main {
  try {
    throw error_NewError("test")
  } catch err: error_Error {
    print("Error Inner:", err.stack)
    throw err
  }
}
======= code =======
======= flags =======
======= stderr =======
